ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_user: ansible
ansible_password: "Ansible123"
ansible_become: yes
ansible_become_method: enable
ansible_become_password: "C0mp@ny123"

vault_login_password: "Ansible123"
vault_enable_password: "C0mp@ny123"

logging_host: 192.168.72.1
ntp_server: 192.168.72.1
