access_interface_ranges:
  - "GigabitEthernet0/1-3"
  - "GigabitEthernet1/0-3"
  - "GigabitEthernet2/0-3"
  - "GigabitEthernet3/0-3"

edge_access_vlans:
  GentV1: 10
  GentV2: 20
  GentV3: 30
  AntwerpenV1: 10
  AntwerpenV2: 20
  AntwerpenV3: 30
  BrusselV1: 10
  BrusselV2: 20
  BrusselV3: 30
