ospf_process: 1
ospf_networks:
  - network: 10.10.10.0
    wildcard: 0.0.0.3
    area: 0
  - network: 10.10.20.0
    wildcard: 0.0.0.3
    area: 0
  - network: 10.10.30.0
    wildcard: 0.0.0.3
    area: 0