vlans:
  - { id: 10, name: HR }
  - { id: 20, name: IT }
  - { id: 30, name: Guest }
  - { id: 99, name: Management }
trunk:
  name: GigabitEthernet0/3
  allowed: "10,20,30,99"
access_ports:
  - { name: GigabitEthernet0/0, vlan: 10 }
  - { name: GigabitEthernet0/1, vlan: 20 }
  - { name: GigabitEthernet0/2, vlan: 30 }

ansible_terminal_length: 0
ansible_terminal_width: 0
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_become_method: enable
