interfaces:
  - name: GigabitEthernet0/0
    description: Link naar CompanyRouter
    ipv4:
      - address: 10.10.20.2/30
  - name: GigabitEthernet0/1
    description: Link naar Uplink switch
    ipv4:
      - address: 192.168.20.1/24