---
interfaces:
  - name: GigabitEthernet0/0
    description: Link naar ComanyRouter
    ip: 10.10.20.2
    mask: 255.255.255.252
  - name: GigabitEthernet0/1
    description: Link naar Uplink switch
    ip: 192.168.20.1
    mask: 255.255.255.0