vlans:
  - id: 10
    name: Verdieping1_Antwerpen
  - id: 20
    name: Verdieping2_Antwerpen
  - id: 30
    name: Verdieping3_Antwerpen
  - id: 99
    name: Management

interfaces:
  - name: GigabitEthernet0/0
    description: Verdieping 1 Antwerpen
    mode: access
    access_vlan: 10
  - name: GigabitEthernet0/1
    description: Verdieping 2 Antwerpen
    mode: access
    access_vlan: 20
  - name: GigabitEthernet0/2
    description: Verdieping 3 Antwerpen
    mode: access
    access_vlan: 30
  - name: GigabitEthernet0/3
    description: Uplink
    mode: trunk
    trunk_allowed_vlans: "1,10,20,30,99"

svi_interfaces:
  - vlan: 99
    ipv4: 192.168.20.5/26

static_routes:
  - address_families:
      - afi: ipv4
        routes:
          - dest: 0.0.0.0/0
            next_hops:
              - forward_router_address: 192.168.20.1
