interfaces:
  - name: GigabitEthernet0/0
    description: Link naar CompanyRouter
    ipv4:
      - address: 10.10.30.2/30
  - name: GigabitEthernet0/1
    description: Link naar Uplink switch
    ipv4:
      - address: 192.168.30.1/24
subinterfaces:
  - name: GigabitEthernet0/1.10
    vlan: 10
    ipv4: 192.168.30.65/26    # 192.168.30.64-127 
  - name: GigabitEthernet0/1.20
    vlan: 20
    ipv4: 192.168.30.129/26   # 192.168.30.128-191 
  - name: GigabitEthernet0/1.30
    vlan: 30
    ipv4: 192.168.30.193/26  # 192.168.30.192-255
  - name: GigabitEthernet0/1.99
    vlan: 99
    ipv4: 192.168.30.1/26   # 192.168.30.0-63

static_routes:
  - address_families:
      - afi: ipv4
        routes:
          - dest: 0.0.0.0/0
            next_hops:
              - forward_router_address: 10.10.30.1
          - dest: 192.168.30.0/24
            next_hops:
              - forward_router_address: 192.168.30.5