interfaces:
  - name: GigabitEthernet0/0
    description: Link naar site Gent
    ipv4:
      - address: 10.10.10.1/30
  - name: GigabitEthernet0/1
    description: Link naar site Antwerpen
    ipv4:
      - address: 10.10.20.1/30
  - name: GigabitEthernet0/2
    description: Link naar site Brussel
    ipv4:
      - address: 10.10.30.1/30
  - name: GigabitEthernet0/3
    description: Management Interface
    ipv4:
      - address: 192.168.72.10/24

nat_acls:
  - afi: ipv4
    acls:
      - name: NAT_GENT
        acl_type: extended
        aces:
          - grant: permit
            protocol: ip
            source:
              address: 192.168.72.0
              wildcard_bits: 0.0.0.255
            destination:
              address: 10.10.10.0
              wildcard_bits: 0.0.0.3
      - name: NAT_ANT
        acl_type: extended
        aces:
          - grant: permit
            protocol: ip
            source:
              address: 192.168.72.0
              wildcard_bits: 0.0.0.255
            destination:
              address: 10.10.20.0
              wildcard_bits: 0.0.0.3
      - name: NAT_BRU
        acl_type: extended
        aces:
          - grant: permit
            protocol: ip
            source:
              address: 192.168.72.0
              wildcard_bits: 0.0.0.255
            destination:
              address: 10.10.30.0
              wildcard_bits: 0.0.0.3

static_routes:
  - address_families:
      - afi: ipv4
        routes:
          - dest: 0.0.0.0/0
            next_hops:
              - forward_router_address: 192.168.72.1