---
interfaces:
  - name: GigabitEthernet0/0
    description: Link naar site Gent
    ip: 10.10.10.1
    mask: 255.255.255.252
  - name: GigabitEthernet0/1
    description: Link naar site Antwerpen
    ip: 10.10.20.1
    mask: 255.255.255.252
  - name: GigabitEthernet0/2
    description: Link naar site Brussel
    ip: 10.10.30.1
    mask: 255.255.255.252
  - name: GigabitEthernet0/3
    description: Management Interface
    ip: 192.168.72.10
    mask: 255.255.255.0
