all:
  children:
    routers:
      hosts:
        CompanyRouter:     { ansible_host: 192.168.72.10 }
        GentRouter:        { ansible_host: 192.168.72.11 }
        AntwerpenRouter:   { ansible_host: 192.168.72.12 }
        BrusselRouter:     { ansible_host: 192.168.72.13 }
    switches:
      hosts:
        GentUplink:  { ansible_host: 172.16.131.50 }
        GentV1:      { ansible_host: 172.16.131.51 }
        GentV2:      { ansible_host: 172.16.131.52 }
        GentV3:      { ansible_host: 172.16.131.53 }
