all:
  children:

    routers:
      hosts:
        CompanyRouter:
          ansible_host: 192.168.72.10
          role_nat: true
          nat_inside: GigabitEthernet0/3
          nat_outside:
            - GigabitEthernet0/0
            - GigabitEthernet0/1
            - GigabitEthernet0/2

        GentRouter:
          ansible_host: 10.10.10.2

        AntwerpenRouter:
          ansible_host: 10.10.20.2

        BrusselRouter:
          ansible_host: 10.10.30.2

    switches:
      children:

        uplink_switches:
          hosts:
            GentUplink:
              ansible_host: 192.168.10.5
            AntwerpenUplink:
              ansible_host: 192.168.20.5
            BrusselUplink:
              ansible_host: 192.168.30.5

        edge_switches:
          hosts:
            GentV1:
              ansible_host: 192.168.10.10
            GentV2:
              ansible_host: 192.168.10.20
            GentV3:
              ansible_host: 192.168.10.30

            AntwerpenV1:
              ansible_host: 192.168.20.10
            AntwerpenV2:
              ansible_host: 192.168.20.20
            AntwerpenV3:
              ansible_host: 192.168.20.30

            BrusselV1:
              ansible_host: 192.168.30.10
            BrusselV2:
              ansible_host: 192.168.30.20
            BrusselV3:
              ansible_host: 192.168.30.30

# groepen per site
    gent:
      children:
        gent_routers:
        gent_switches:

    gent_routers:
      hosts:
        GentRouter:

    gent_switches:
      hosts:
        GentUplink:
        GentV1:
        GentV2:
        GentV3:

    antwerpen:
      children:
        antwerpen_routers:
        antwerpen_switches:

    antwerpen_routers:
      hosts:
        AntwerpenRouter:

    antwerpen_switches:
      hosts:
        AntwerpenUplink:
        AntwerpenV1:
        AntwerpenV2:
        AntwerpenV3:

    brussel:
      children:
        brussel_routers:
        brussel_switches:

    brussel_routers:
      hosts:
        BrusselRouter:

    brussel_switches:
      hosts:
        BrusselUplink:
        BrusselV1:
        BrusselV2:
        BrusselV3:
