all:
  children:
    routers:
      hosts:
        CompanyRouter:
          ansible_host: 192.168.72.10
          role_nat: true
          nat_inside: "GigabitEthernet0/3"
          nat_outside:
            - "GigabitEthernet0/0"
            - "GigabitEthernet0/1"
            - "GigabitEthernet0/2"
          nat_sites:
            - { name: "NAT_GENT", dest: "10.10.10.0 0.0.0.3", interface: "GigabitEthernet0/0" }
            - { name: "NAT_ANT",  dest: "10.10.20.0 0.0.0.3", interface: "GigabitEthernet0/1" }
            - { name: "NAT_BRU",  dest: "10.10.30.0 0.0.0.3", interface: "GigabitEthernet0/2" }
        GentRouter:        { ansible_host: 10.10.10.2 }
        AntwerpenRouter:   { ansible_host: 10.10.20.2 }
        BrusselRouter:     { ansible_host: 10.10.30.2 }
    switches:
      hosts:
        GentUplink:  { ansible_host: 172.16.131.50 }
        GentV1:      { ansible_host: 172.16.131.51 }
        GentV2:      { ansible_host: 172.16.131.52 }
        GentV3:      { ansible_host: 172.16.131.53 }
