---
ospf_process: 1
ospf_networks:
  - address: 10.10.10.0
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 10.10.20.0
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 10.10.30.0
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 192.168.10.0
    wildcard_bits: 0.0.0.255
    area: 0
  - address: 192.168.20.0
    wildcard_bits: 0.0.0.255
    area: 0
  - address: 192.168.30.0
    wildcard_bits: 0.0.0.255
    area: 0